// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vqpnskjrkelmgcymgisy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZxcG5za2pya2VsbWdjeW1naXN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQxNzg5MTYsImV4cCI6MjA0OTc1NDkxNn0.LQgtythNxAoWe-Cg9xBWmg2Xfw_fg8HgVMpKswyalYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);